# Generated by Django 5.0.7 on 2024-09-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_certification_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='year',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
